# Auto-generated by scripts/load-local-env.ps1
GATEWAY_HOST = '10.229.90.208'
GATEWAY_PORT = 9000
HOME_ID = 1
DEVICE_TOKEN = 'ohstem-demo-token'
RUNTIME_DEVICE_ID = 1
WIFI_SSID = 'Test'
WIFI_PASS = '12345678'
