package com.java.domain;

public enum AlertType {
    CRITICAL_TEMP,
    DEVICE_OFFLINE,
    SENSOR_ERROR,
    HIGH_HUMIDITY,
    LOW_HUMIDITY,
    LOW_LIGHT,
    HIGH_LIGHT,
    MOTION_DETECTED,
    CUSTOM,
    HIGH_TEMPERATURE,
    LOW_TEMPERATURE,
    WRONG_PASSWORD
}