param(
    [string]$LanHost = "",
    [int]$GatewayPort = 9000,
    [string]$EnvFile = ".env.local",
    [switch]$Persist,
    [switch]$SkipWriteFiles
)

$Root = Split-Path $PSScriptRoot -Parent
$RootEnv = Join-Path $Root ".env"
$LocalEnv = Join-Path $Root $EnvFile

function Read-EnvFile {
    param([string]$Path)

    if (-not (Test-Path $Path)) {
        return @{}
    }

    $values = @{}
    Get-Content $Path | ForEach-Object {
        $line = $_.Trim()
        if ([string]::IsNullOrWhiteSpace($line) -or $line.StartsWith("#") -or -not $line.Contains("=")) {
            return
        }

        $parts = $line -split "=", 2
        $name = $parts[0].Trim()
        $value = $parts[1].Trim().Trim('"').Trim("'")
        if ($name) {
            $values[$name] = $value
        }
    }
    return $values
}

function Find-LanHost {
    $blocks = ((ipconfig) -join "`n") -split "(\r?\n){2,}"
    foreach ($block in $blocks) {
        if ($block -match "Default Gateway[^\r\n]*:\s*(\d{1,3}(\.\d{1,3}){3})" -and
            $block -match "IPv4 Address[^\r\n]*:\s*(\d{1,3}(\.\d{1,3}){3})") {
            $candidate = $Matches[1]
            if ($candidate -notlike "127.*" -and $candidate -notlike "169.254.*") {
                return $candidate
            }
        }
    }

    foreach ($block in $blocks) {
        if ($block -match "IPv4 Address[^\r\n]*:\s*(\d{1,3}(\.\d{1,3}){3})") {
            $candidate = $Matches[1]
            if ($candidate -notlike "127.*" -and $candidate -notlike "169.254.*") {
                return $candidate
            }
        }
    }

    return "127.0.0.1"
}

$base = Read-EnvFile $RootEnv
foreach ($key in $base.Keys) {
    Set-Item -Path "Env:$key" -Value $base[$key]
}

if ([string]::IsNullOrWhiteSpace($LanHost)) {
    $LanHost = Find-LanHost
}

$gatewayToken = if ($env:GATEWAY_DEVICE_TOKEN) { $env:GATEWAY_DEVICE_TOKEN } else { "ohstem-demo-token" }
$homeId = if ($env:HOME_ID) { $env:HOME_ID } else { "1" }
$wifiSsid = if ($env:AIOT_WIFI_SSID) { $env:AIOT_WIFI_SSID } elseif ($env:WIFI_SSID) { $env:WIFI_SSID } else { "Test" }
$wifiPass = if ($env:AIOT_WIFI_PASS) { $env:AIOT_WIFI_PASS } elseif ($env:WIFI_PASS) { $env:WIFI_PASS } else { "12345678" }

$local = [ordered]@{
    "DB_URL" = "jdbc:postgresql://localhost:5432/smarthouse"
    "DB_USERNAME" = if ($env:DB_USERNAME) { $env:DB_USERNAME } else { "postgres" }
    "DB_PASSWORD" = if ($env:DB_PASSWORD) { $env:DB_PASSWORD } else { "123456" }
    "JPA_DDL_AUTO" = "validate"
    "FLYWAY_ENABLED" = "true"
    "FLYWAY_BASELINE_ON_MIGRATE" = "true"
    "SPRING_RABBITMQ_HOST" = "localhost"
    "SPRING_RABBITMQ_PORT" = "5672"
    "SPRING_RABBITMQ_SSL_ENABLED" = "false"
    "APP_NOTIFICATION_MAIL_ENABLED" = "false"
    "APP_TELEGRAM_ENABLED" = "false"
    "VITE_API_BASE_URL" = "http://localhost:8080"
    "VITE_GOOGLE_REDIRECT_URI" = "http://localhost:5173/auth/google/callback"
    "BACKEND_BASE" = "http://localhost:8080"
    "YOLO_BASE" = "http://127.0.0.1:5000"
    "GATEWAY_HOST" = "0.0.0.0"
    "GATEWAY_CLIENT_HOST" = $LanHost
    "GATEWAY_PORT" = "$GatewayPort"
    "GATEWAY_DEVICE_TOKEN" = $gatewayToken
    "HOME_ID" = $homeId
    "ALLOWED_DEVICE_IDS" = if ($env:ALLOWED_DEVICE_IDS) { $env:ALLOWED_DEVICE_IDS } else { "1,2,3" }
    "ALLOWED_DEVICE_KEYS" = if ($env:ALLOWED_DEVICE_KEYS) { $env:ALLOWED_DEVICE_KEYS } else { "yolobit-01,ohstem-fan-ctrl-01,ohstem-light-ctrl-01,ohstem-temp-01,ohstem-humidity-01,ohstem-light-01,ohstem-motion-01" }
    "ALLOW_YOLO" = "true"
}

foreach ($key in $local.Keys) {
    Set-Item -Path "Env:$key" -Value $local[$key]
    if ($Persist) {
        [Environment]::SetEnvironmentVariable($key, $local[$key], "User")
    }
}

if (-not $SkipWriteFiles) {
    $envLines = $local.GetEnumerator() | ForEach-Object { "$($_.Key)=$($_.Value)" }
    Set-Content -Path $LocalEnv -Value $envLines -Encoding UTF8

    $aiotConfig = @(
        "# Auto-generated by scripts/load-local-env.ps1",
        "GATEWAY_HOST = '$LanHost'",
        "GATEWAY_PORT = $GatewayPort",
        "HOME_ID = $homeId",
        "DEVICE_TOKEN = '$gatewayToken'",
        "RUNTIME_DEVICE_ID = 1",
        "WIFI_SSID = '$wifiSsid'",
        "WIFI_PASS = '$wifiPass'"
    )
    Set-Content -Path (Join-Path $Root "aiot_local_config.py") -Value $aiotConfig -Encoding UTF8
}

Write-Host "Local env loaded."
Write-Host "Backend: http://localhost:8080"
Write-Host "Gateway bind: 0.0.0.0:$GatewayPort"
Write-Host "Gateway LAN client URL: http://${LanHost}:$GatewayPort"
Write-Host "Frontend API: http://localhost:8080"
Write-Host "Generated: $LocalEnv"
Write-Host "Generated: $(Join-Path $Root 'aiot_local_config.py')"
